services:
  postgres-db:
    image: postgres:15-alpine
    container_name: sandbox-postgres
    environment:
      POSTGRES_USER: sandbox_user
      POSTGRES_PASSWORD: sandbox_password
      POSTGRES_DB: sandbox_api_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
